export const PLANT_STAGES = [
    { id: "Saved", step: "01", label: "Saved", emoji: "🌱", title: "Seed planted", short: "A promising role has caught your eye.", description: "Spotted something interesting? Drop the link in seconds—add the company, role, and a quick note before that tab disappears forever.", color: "#4f8cff", tint: "#eaf2ff", soil: "Seed planted" },
    { id: "Applied", step: "02", label: "Applied", emoji: "🪴", title: "First leaves", short: "Your first official step into the pipeline.", description: "Hit submit. Log the date, salary expectations, and location so the application has a home and a next step.", color: "#35a76a", tint: "#eaf8ee", soil: "Growing" },
    { id: "Screening", step: "03", label: "Screening", emoji: "🌿", title: "Taking root", short: "A warm lead is beginning to grow.", description: "Recruiter call or take-home test? Set a reminder date so you follow up at the right time and never let a warm lead go cold.", color: "#a26bea", tint: "#f3edff", soil: "Taking root" },
    { id: "Interview", step: "04", label: "Interview", emoji: "🌳", title: "Branching out", short: "Your preparation can make this branch stronger.", description: "Interviews are booked. Open Interview Prep for questions tailored to the role and company, then practice out loud in the mock room.", color: "#e79b31", tint: "#fff4df", soil: "Branching out" },
    { id: "Offer", step: "05", label: "Offer", emoji: "🌸", title: "Fully bloomed", short: "The garden grew toward this moment.", description: "You did it. Log the offer details, compare packages if you have multiple, and celebrate the progress you made along the way.", color: "#15956c", tint: "#e4f8f0", soil: "Fully bloomed" },
    { id: "Rejected", step: "06", label: "Rejected", emoji: "🍂", title: "Fallen leaf", short: "Not every seed blooms—and that is part of the process.", description: "Keep the record, see your response rate in Stats, and carry the momentum forward. A fallen leaf still feeds the soil for the next season.", color: "#7f8b86", tint: "#eef1ef", soil: "Fallen leaf" },
];

export function stageInfo(status) { return PLANT_STAGES.find(stage => stage.id === status) || PLANT_STAGES[0]; }
