export const PLANT_STAGES = [
    { id: "Saved", backendStatus: "SAVED", step: "01", label: "Saved", gardenName: "SEED", statusText: "Saved", emoji: "🌱", title: "Seed", short: "An opportunity worth exploring.", description: "Save the opportunity while the signal is fresh. Add the company, role, source, and a note so a promising lead has a place to grow.", color: "#4f8cff", tint: "#eaf2ff", soil: "Seed" },
    { id: "Applied", backendStatus: "APPLIED", step: "02", label: "Applied", gardenName: "SPROUT", statusText: "Applied", emoji: "🪴", title: "Sprout", short: "Your application has entered the world.", description: "Log the application date and source after you submit. The role now has a clear next move instead of disappearing into another tab.", color: "#35a76a", tint: "#eaf8ee", soil: "Sprout" },
    { id: "Screening", backendStatus: "UNDER_REVIEW", step: "03", label: "Screening", gardenName: "SAPLING", statusText: "Under review", emoji: "🌿", title: "Sapling", short: "The opportunity is taking root.", description: "A recruiter screen, assessment, or take-home is a sign of momentum. Capture the next date and prepare around the signals the role is asking for.", color: "#a26bea", tint: "#f3edff", soil: "Sapling" },
    { id: "Interview", backendStatus: "INTERVIEW", step: "04", label: "Interview", gardenName: "BRANCHING", statusText: "Interview", emoji: "🌳", title: "Branching", short: "Conversations are creating new branches.", description: "The conversation is close. Open Interview Prep for company research, role-specific questions, and a mock interview that makes your evidence easier to reach.", color: "#e79b31", tint: "#fff4df", soil: "Branching" },
    { id: "Offer", backendStatus: "OFFER", step: "05", label: "Offer", gardenName: "BLOOM", statusText: "Hired", emoji: "🌸", title: "Bloom", short: "The opportunity has bloomed.", description: "Log the offer details and reflect on the work that got you here. Your preparation becomes evidence you can carry into the next opportunity.", color: "#15956c", tint: "#e4f8f0", soil: "Bloom" },
    { id: "Rejected", backendStatus: "REJECTED", step: "06", label: "Rejected", gardenName: "DORMANT", statusText: "Rejected", emoji: "🍂", title: "Dormant", short: "Every season leaves something behind.", description: "Keep the record without calling the journey a failure. Capture what you learned, let the old leaves fall, and carry the useful signal into the next search.", color: "#7f8b86", tint: "#eef1ef", soil: "Dormant" },
];

export function stageInfo(status) { return PLANT_STAGES.find(stage => stage.id === status || stage.backendStatus === String(status || "").toUpperCase()) || PLANT_STAGES[0]; }
