import React, { useState } from "react";
import { ArrowRight, CheckCircle2, LayoutGrid, List, Sprout } from "lucide-react";
import SectionContainer from "./SectionContainer";
import { LANDING_STAGES, SAMPLE_APPLICATIONS } from "./landingData";
import StageIcon from "../../StageIcon";

const VIEWS = ["Garden", "Board", "List"];

export default function ApplicationViews({ onStart }) {
    const [view, setView] = useState("Garden");
    return <SectionContainer id="application-views" variant="forest" className="landing-application-views" eyebrow="08 / APPLICATION VIEWS" title={<>Use the view<br /><em>that fits the moment.</em></>} description="Move from a calm garden view to a practical board or a detailed list without changing the underlying application record."><div className="landing-view-tabs" role="tablist" aria-label="Application views">{VIEWS.map(label => <button type="button" role="tab" aria-selected={view === label} className={view === label ? "is-active" : ""} key={label} onClick={() => setView(label)}>{label === "Garden" ? <Sprout size={15} /> : label === "Board" ? <LayoutGrid size={15} /> : <List size={15} />}{label}</button>)}</div>{view === "Garden" && <div className="landing-view-garden"><div className="landing-view-garden-head"><span>YOUR APPLICATION GARDEN</span><small>hover a plot to inspect the role</small></div><div className="landing-view-garden-surface">{SAMPLE_APPLICATIONS.map((application, index) => <button type="button" className={`landing-view-plot view-plot-${index + 1}`} key={application.company} onClick={onStart}><StageIcon stage={application.stage} size={29} /><span><b>{application.company}</b><small>{application.stage.gardenName}</small></span></button>)}</div></div>}{view === "Board" && <div className="landing-board-view">{LANDING_STAGES.map(stage => <div className="landing-board-column" key={stage.id}><header><span>{stage.gardenName}</span><small>{stage.id === "Interview" ? 2 : stage.id === "Rejected" ? 1 : stage.id === "Offer" ? 1 : 3}</small></header><div className="landing-board-card"><span className="landing-board-card-icon"><StageIcon stage={stage} size={16} /></span><b>{stage.id === "Interview" ? "Google" : stage.id === "Offer" ? "Shopify" : stage.id === "Rejected" ? "Airbnb" : stage.id === "Saved" ? "Linear" : stage.id === "Applied" ? "Stripe" : "Notion"}</b><small>{stage.statusText || stage.label}</small><CheckCircle2 size={13} /></div></div>)}</div>}{view === "List" && <div className="landing-list-view"><div className="landing-list-row landing-list-head"><span>Company / role</span><span>Stage</span><span>Next action</span><span>Updated</span></div>{[["Google", "Senior Backend Engineer", "BRANCHING", "Practice system design"], ["Stripe", "Platform Engineer", "SAPLING", "Follow up Friday"], ["Linear", "Senior Frontend Engineer", "SEED", "Review brief"], ["Shopify", "Staff Engineer", "BLOOM", "Compare offer"]].map(([company, role, stage, action]) => <button type="button" className="landing-list-row" key={company} onClick={onStart}><span><b>{company}</b><small>{role}</small></span><strong>{stage}</strong><span>{action}</span><small>Today</small><ArrowRight size={13} /></button>)}</div>}</SectionContainer>;
}
