import React, { useState } from "react";
import { ArrowRight, Leaf } from "lucide-react";
import SectionContainer from "./SectionContainer";
import { LANDING_STAGES } from "./landingData";
import StageIcon from "../../StageIcon";

const EXAMPLES = ["Linear · Senior Frontend Engineer", "Stripe · Platform Engineer", "Notion · Senior Software Engineer", "Google · Senior Backend Engineer", "Shopify · Staff Engineer", "Airbnb · Senior Engineer"];

export default function GrowthJourney({ onStart }) {
    const [selected, setSelected] = useState("Interview");
    const active = LANDING_STAGES.find(stage => stage.id === selected) || LANDING_STAGES[3];
    return <SectionContainer id="growth" variant="forest" className="landing-growth-section" eyebrow="03 / GROWTH JOURNEY" title={<>Six stages.<br /><em>One clear path.</em></>} description="Click a stage to see the next move."><div className="landing-growth-diagram"><div className="landing-growth-main-line" aria-hidden="true" />{LANDING_STAGES.slice(0, 5).map(stage => <button type="button" key={stage.id} className={`landing-growth-node ${selected === stage.id ? "is-selected" : ""}`} onClick={() => setSelected(stage.id)} aria-pressed={selected === stage.id}><span className="landing-growth-node-step">{stage.step}</span><span className="landing-growth-node-art"><StageIcon stage={stage} size={28} /></span><strong>{stage.gardenName}</strong><small>{stage.statusText || stage.label}</small></button>)}<span className="landing-growth-branch-line" aria-hidden="true" /><button type="button" className={`landing-growth-node landing-growth-dormant ${selected === "Rejected" ? "is-selected" : ""}`} onClick={() => setSelected("Rejected")} aria-pressed={selected === "Rejected"}><span className="landing-growth-node-step">06</span><span className="landing-growth-node-art"><StageIcon stage={LANDING_STAGES[5]} size={28} /></span><strong>DORMANT</strong><small>Rejected</small></button></div><div className="landing-growth-detail"><div className="landing-growth-plant-panel"><div className="landing-growth-plant-top"><span><Leaf size={14} /> ROLE STATUS</span><small>{active.step} / 06</small></div><div className="landing-growth-plant-art"><span className="landing-growth-orbit" /><span className="landing-growth-orbit landing-growth-orbit-small" /><StageIcon stage={active} size={92} strokeWidth={1.15} /><div className="landing-growth-plant-caption"><b>{active.gardenName}</b><small>{active.short}</small></div></div></div><div className="landing-growth-copy"><span className="landing-eyebrow">{active.step} / {active.gardenName}</span><h3>{active.statusText || active.label}</h3><p>{active.description}</p><div className="landing-growth-example"><small>ROLE</small><strong>{EXAMPLES[Math.max(0, Number(active.step) - 1)]}</strong><span>{active.short}</span></div><button type="button" className="landing-outline-button" onClick={onStart}>Open garden <ArrowRight size={14} /></button></div></div></SectionContainer>;
}
