import React, { useEffect, useState } from "react";
import { ArrowRight, Check, ChevronDown, Leaf, LockKeyhole, Mail, Mic, Sprout, Sparkles, Target, TreePine, WandSparkles } from "lucide-react";
import { BrowserRouter, Navigate, Route, Routes, useNavigate } from "react-router-dom";
import Workspace from "./Workspace";
import { DEMO_USER, isSupabaseConfigured, supabase } from "./lib/supabase";
import { PLANT_STAGES } from "./lib/plantStages";

function Landing() {
    const navigate = useNavigate(); const [activeStage, setActiveStage] = useState("Saved"); const active = PLANT_STAGES.find(stage => stage.id === activeStage) || PLANT_STAGES[0];
    return <div className="landing-page botanical-landing">
        <div className="landing-noise" />
        <nav className="landing-nav"><div className="brand landing-brand"><div className="brand-mark plant-mark"><Sprout size={18} /></div><div><strong>track<span>.</span></strong><small>grow your next move</small></div></div><div className="landing-links"><a href="#garden">The garden</a><a href="#stages">Six stages</a><a href="#practice">Practice room</a></div><button className="outline-dark-btn" onClick={() => navigate("/login")}>Enter your garden <ArrowRight size={15} /></button></nav>
        <main>
            <section className="garden-hero"><div className="hero-leaf leaf-a">✦</div><div className="hero-leaf leaf-b">✦</div><div className="hero-copy garden-hero-copy"><span className="garden-kicker"><span className="kicker-dot" />A calmer job search, grown with intention</span><h1>Plant the seed.<br /><em>Grow the opportunity.</em></h1><p>Track every application like a living garden. Give each role the right care, watch your pipeline grow, and walk into interviews with roots beneath your story.</p><div className="hero-actions"><button className="garden-primary" onClick={() => navigate("/login")}>Start your garden <ArrowRight size={16} /></button><a href="#stages" className="garden-text-link">See the growth cycle <ChevronDown size={15} /></a></div><div className="garden-trust"><span><LockKeyhole size={13} />Private by default</span><i /><span><Leaf size={13} />Built for steady progress</span></div></div><div className="hero-garden-art" aria-hidden="true"><div className="sun-orb" /><div className="hero-plant"><div className="hero-stem" /><div className="hero-leaf-shape leaf-left" /><div className="hero-leaf-shape leaf-right" /><div className="hero-bloom">✦</div></div><div className="hero-pot"><div className="pot-rim" /><div className="pot-body" /><div className="pot-shadow" /></div><div className="hero-card card-one"><span>Today’s care</span><b>Practice 1 answer</b><small>20 minutes · interview prep</small></div><div className="hero-card card-two"><span>Garden health</span><b>74% ready</b><div><i style={{ width: "74%" }} /></div></div><div className="hero-card card-three"><span>Next bloom</span><b>Offer stage</b><small>Keep showing up</small></div></div></section>
            <section className="garden-ribbon"><div><b>One pipeline.</b><span>Six visible stages.</span></div><div className="ribbon-steps">{PLANT_STAGES.map((stage, index) => <button key={stage.id} className={stage.id === activeStage ? "ribbon-step active" : "ribbon-step"} onClick={() => { setActiveStage(stage.id); document.getElementById("stages")?.scrollIntoView({ behavior: "smooth" }); }}><span>{stage.emoji}</span><small>{stage.label}</small>{index < PLANT_STAGES.length - 1 && <i />}</button>)}</div></section>
            <section className="garden-section stage-section" id="stages"><div className="garden-section-heading"><div><span className="garden-overline">The growth cycle</span><h2>Every “no” is soil.<br /><em>Every “yes” is a bloom.</em></h2></div><p>Flip each card to see what to capture at that stage. The tracker is not just a list—it is a small, living system for your search.</p></div><div className="stage-grid">{PLANT_STAGES.map(stage => <PlantCard key={stage.id} stage={stage} flipped={stage.id === activeStage} onToggle={() => setActiveStage(stage.id)} />)}</div><div className="stage-callout" style={{ background: active.tint, borderColor: `${active.color}33` }}><div className="callout-emoji">{active.emoji}</div><div><span>Stage {active.step} · {active.soil}</span><b>{active.short}</b></div><button onClick={() => navigate("/login")} style={{ color: active.color }}>Add your first {active.label.toLowerCase()} <ArrowRight size={14} /></button></div></section>
            <section className="garden-section garden-workflow" id="garden"><div className="workflow-copy"><span className="garden-overline">A garden that works</span><h2>Your search gets<br /><em>better with care.</em></h2><p>Save the role, write down the next step, prepare for the conversation, and let the small actions compound. Track turns scattered effort into a visible path forward.</p><button className="garden-primary" onClick={() => navigate("/login")}>Open the workspace <ArrowRight size={15} /></button></div><div className="workflow-board"><div className="board-vine" /><div className="workflow-board-top"><span><i />track. / today</span><small>your garden is growing</small></div><div className="workflow-board-head"><div><span>Good morning, Alex</span><b>Let’s tend to one thing.</b></div><div className="tiny-avatar">AM</div></div><div className="workflow-metrics"><div><small>Active plants</small><b>12</b><span>+2 this month</span></div><div><small>In bloom</small><b>04</b><span>interviews ready</span></div><div><small>Garden health</small><b>74%</b><span>strong foundation</span></div></div><div className="workflow-progress"><div><span><b>Pipeline growth</b><small>this season</small></span><strong>68%</strong></div><div className="growth-line"><i style={{ width: "68%" }} /></div><div className="mini-seed-row">{PLANT_STAGES.slice(0, 5).map(stage => <span key={stage.id} className={stage.id === "Interview" ? "grown" : ""}>{stage.emoji}</span>)}</div></div></div></section>
            <section className="garden-section practice-section" id="practice"><div className="practice-leaf-art"><div className="practice-plant"><div /><i /><i /></div></div><div className="practice-copy"><span className="garden-overline">Before the bloom</span><h2>Practice until your story<br /><em>has roots.</em></h2><p>Role-specific prep turns a job description into questions worth answering. The voice room helps you hear what is clear, what is missing, and what to make memorable.</p><div className="practice-points"><span><Check size={14} />Role-specific question sets</span><span><Check size={14} />STAR story bank</span><span><Check size={14} />Voice practice with useful ratings</span></div><button className="garden-light-btn" onClick={() => navigate("/login")}><Mic size={15} />Try the practice room</button></div></section>
        </main><footer className="garden-footer"><div className="brand"><div className="brand-mark plant-mark"><Sprout size={16} /></div><strong>track<span>.</span></strong></div><span>For the next thoughtful move.</span><a href="#stages">Back to the garden <ArrowRight size={14} /></a></footer>
    </div>;
}

function PlantCard({ stage, flipped, onToggle }) { return <button className={flipped ? "plant-card is-flipped" : "plant-card"} onClick={onToggle} aria-label={`${stage.label} stage details`}><span className="plant-card-inner"><span className="plant-card-face plant-card-front"><span className="card-orbit orbit-one" /><span className="card-orbit orbit-two" /><span className="stage-number">{stage.step}</span><span className="stage-emoji">{stage.emoji}</span><span className="stage-label">{stage.label}</span><span className="stage-line" style={{ background: stage.color }} /><small>{flipped ? "Click to close" : "Click to explore"}</small></span><span className="plant-card-face plant-card-back" style={{ background: `linear-gradient(145deg, ${stage.color}, #183c2a)` }}><span className="stage-number">{stage.step}</span><strong>{stage.label} {stage.emoji}</strong><p>{stage.description}</p><span className="plant-card-footer"><i />{stage.title}</span></span></span></button>; }

function Login() { const navigate = useNavigate(); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const signIn = async () => { setLoading(true); if (isSupabaseConfigured) { const { error: authError } = await supabase.auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${window.location.origin}/dashboard` } }); if (authError) setError(authError.message); } else navigate("/dashboard"); setLoading(false); }; return <div className="auth-page botanical-auth"><div className="auth-side plant-auth-side"><button className="back-link" onClick={() => navigate("/")}><ArrowRight size={14} style={{ transform: "rotate(180deg)" }} />Back to the garden</button><div className="auth-side-copy"><span className="garden-kicker"><span className="kicker-dot" />Your next move starts here</span><h1>Give your search<br /><em>some sunlight.</em></h1><p>A home for the roles you want, the stories you tell, and the confidence you grow along the way.</p></div><div className="auth-testimonial"><span>“</span><p>I stopped treating my search like a spreadsheet and started seeing the story it was growing into.</p><small>— Product designer, 2026</small></div></div><div className="auth-main"><div className="auth-card botanical-auth-card"><div className="brand dark centered"><div className="brand-mark plant-mark"><Sprout size={18} /></div><div><strong>track<span>.</span></strong><small>grow your next move</small></div></div><h2>Welcome back</h2><p>Come tend to your garden.</p>{error && <div className="auth-error">{error}</div>}<button className="google-btn" onClick={signIn} disabled={loading}><span className="google-g">G</span>{loading ? "Opening your garden…" : isSupabaseConfigured ? "Continue with Google" : "Continue to demo garden"}<ArrowRight size={15} /></button><div className="auth-divider"><span>or</span></div><button className="demo-btn" onClick={() => navigate("/dashboard")}><Sprout size={15} />Explore with sample garden <ArrowRight size={15} /></button><p className="auth-note">Demo plants stay in this browser. Connect Supabase for production sync.</p></div></div></div>; }

function Authenticated() { const [user, setUser] = useState(DEMO_USER); const navigate = useNavigate(); useEffect(() => { if (!supabase) return undefined; supabase.auth.getSession().then(({ data }) => { if (data.session) setUser(data.session.user); }); const { data: listener } = supabase.auth.onAuthStateChange((_, session) => setUser(session?.user || DEMO_USER)); return () => listener.subscription.unsubscribe(); }, []); const signOut = async () => { if (supabase) await supabase.auth.signOut(); setUser(DEMO_USER); navigate("/"); }; return <Workspace user={user} onSignOut={signOut} />; }

export default function AppNew() { return <BrowserRouter><Routes><Route path="/" element={<Landing />} /><Route path="/login" element={<Login />} /><Route path="/dashboard/*" element={<Authenticated />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></BrowserRouter>; }
