import React, { useEffect, useState } from "react";
import { ArrowDownRight, ArrowRight, Check, Leaf, LockKeyhole, Mic, MoveUpRight, Sprout } from "lucide-react";
import { BrowserRouter, Navigate, Route, Routes, useNavigate } from "react-router-dom";
import Workspace from "./Workspace";
import { DEMO_USER, isSupabaseConfigured, supabase } from "./lib/supabase";
import { PLANT_STAGES } from "./lib/plantStages";

function Landing() {
    const navigate = useNavigate(); const [activeStage, setActiveStage] = useState("Saved"); const active = PLANT_STAGES.find(stage => stage.id === activeStage) || PLANT_STAGES[0];
    return <div className="editorial-landing">
        <header className="editorial-nav"><div className="editorial-logo"><span className="editorial-logo-mark"><Sprout size={17} /></span><span>track<span className="logo-dot">.</span></span></div><div className="editorial-nav-links"><a href="#journey">The journey</a><a href="#method">The method</a><a href="#practice">Practice</a></div><button className="editorial-nav-cta" onClick={() => navigate("/login")}>Open your garden <MoveUpRight size={14} /></button></header>
        <main>
            <section className="editorial-hero"><div className="hero-grid-lines" /><div className="editorial-hero-copy"><span className="editorial-eyebrow"><i />A calmer way to search</span><h1>Let your next<br /><em>move grow.</em></h1><p>Track every role with the care it deserves. Keep the signal, lose the scramble, and build the kind of confidence that shows up when it matters.</p><div className="editorial-hero-actions"><button className="editorial-primary" onClick={() => navigate("/login")}>Plant your first seed <ArrowRight size={15} /></button><a href="#journey">Explore the journey <ArrowDownRight size={15} /></a></div><div className="editorial-proof"><span><LockKeyhole size={12} />Your data stays yours</span><span><Leaf size={12} />Designed for steady progress</span></div></div><div className="editorial-hero-art"><div className="art-label label-top"><span>01 / 06</span><b>the beginning</b></div><div className="art-sun" /><div className="art-image-slot" aria-label="Future 3D image placement"><div className="art-ring ring-a" /><div className="art-ring ring-b" /><div className="art-ground" /><div className="art-plant"><div className="art-stem" /><div className="art-leaf art-leaf-left" /><div className="art-leaf art-leaf-right" /><div className="art-seed">✦</div></div><div className="art-pot"><span /><i /></div><div className="art-glow" /></div><div className="art-label label-bottom"><span>your search</span><b>in good hands</b></div><div className="art-note note-a"><span>GARDEN HEALTH</span><b>74%</b><i><em /></i></div><div className="art-note note-b"><span>NEXT CARE</span><b>Practice an answer</b><small>20 min · interview prep</small></div></div></section>
            <section className="editorial-metrics"><div><strong>01</strong><span>space for every application</span></div><div><strong>06</strong><span>clear growth stages</span></div><div><strong>∞</strong><span>small moves that compound</span></div><p>Not another spreadsheet.<br /><b>A garden for your momentum.</b></p></section>
            <section className="editorial-journey" id="journey"><div className="journey-heading"><span className="editorial-eyebrow dark"><i />The growth cycle</span><h2>Every role has<br /><em>a season.</em></h2><p>From the first spark of interest to the offer you have worked toward, every stage deserves a different kind of attention.</p></div><div className="journey-layout"><div className="journey-list">{PLANT_STAGES.map(stage => <button key={stage.id} className={stage.id === activeStage ? "journey-item active" : "journey-item"} onClick={() => setActiveStage(stage.id)}><span className="journey-number">{stage.step}</span><span className="journey-emoji">{stage.emoji}</span><span className="journey-label"><b>{stage.label}</b><small>{stage.title}</small></span><ArrowRight size={15} /></button>)}</div><div className="journey-feature" style={{ "--stage-color": active.color, "--stage-tint": active.tint }}><div className="feature-top"><span>Stage {active.step}</span><b>{active.soil}</b></div><div className="feature-symbol">{active.emoji}</div><h3>{active.label}</h3><p>{active.description}</p><div className="feature-footer"><span><i />{active.short}</span><button onClick={() => navigate("/login")}>Add this to your garden <MoveUpRight size={14} /></button></div></div></div></section>
            <section className="editorial-method" id="method"><div className="method-intro"><span className="editorial-eyebrow dark"><i />The track method</span><h2>Keep the story<br /><em>in motion.</em></h2><p>Good searches are not built from frantic bursts. They are built from simple rituals you can return to.</p></div><div className="method-cards"><article><span>01</span><div className="method-icon"><Sprout size={17} /></div><h3>Capture the seed</h3><p>Save the role, why it matters, and the one thing you want to remember before the tab closes.</p></article><article><span>02</span><div className="method-icon"><Leaf size={17} /></div><h3>Tend the next step</h3><p>Give every application a date and a small action. Momentum becomes visible when it has somewhere to go.</p></article><article id="practice"><span>03</span><div className="method-icon"><Mic size={17} /></div><h3>Practice the bloom</h3><p>Turn the job description into role-specific questions, then practice your answer out loud until it has roots.</p></article></div></section>
            <section className="editorial-cta"><div className="cta-orbit orbit-one" /><div className="cta-orbit orbit-two" /><div className="cta-copy"><span className="editorial-eyebrow"><i />Your next season starts here</span><h2>Make room for<br /><em>the right work.</em></h2><p>A beautiful, focused home for the search you are already doing.</p><button className="editorial-primary light" onClick={() => navigate("/login")}>Enter the garden <ArrowRight size={15} /></button></div><div className="cta-seed">✦</div></section>
        </main><footer className="editorial-footer"><div className="editorial-logo"><span className="editorial-logo-mark"><Sprout size={17} /></span><span>track<span className="logo-dot">.</span></span></div><span>For the next thoughtful move.</span><a href="#journey">Back to the garden <ArrowRight size={14} /></a></footer>
    </div>;
}

function Login() { const navigate = useNavigate(); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const signIn = async () => { setLoading(true); if (isSupabaseConfigured) { const { error: authError } = await supabase.auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${window.location.origin}/dashboard` } }); if (authError) setError(authError.message); } else navigate("/dashboard"); setLoading(false); }; return <div className="auth-page botanical-auth"><div className="auth-side plant-auth-side"><button className="back-link" onClick={() => navigate("/")}><ArrowRight size={14} style={{ transform: "rotate(180deg)" }} />Back to the garden</button><div className="auth-side-copy"><span className="garden-kicker"><span className="kicker-dot" />Your next move starts here</span><h1>Give your search<br /><em>some sunlight.</em></h1><p>A home for the roles you want, the stories you tell, and the confidence you grow along the way.</p></div><div className="auth-testimonial"><span>“</span><p>I stopped treating my search like a spreadsheet and started seeing the story it was growing into.</p><small>— Product designer, 2026</small></div></div><div className="auth-main"><div className="auth-card botanical-auth-card"><div className="brand dark centered"><div className="brand-mark plant-mark"><Sprout size={18} /></div><div><strong>track<span>.</span></strong><small>grow your next move</small></div></div><h2>Welcome back</h2><p>Come tend to your garden.</p>{error && <div className="auth-error">{error}</div>}<button className="google-btn" onClick={signIn} disabled={loading}><span className="google-g">G</span>{loading ? "Opening your garden…" : isSupabaseConfigured ? "Continue with Google" : "Continue to demo garden"}<ArrowRight size={15} /></button><div className="auth-divider"><span>or</span></div><button className="demo-btn" onClick={() => navigate("/dashboard")}><Sprout size={15} />Explore with sample garden <ArrowRight size={15} /></button><p className="auth-note">Demo plants stay in this browser. Connect Supabase for production sync.</p></div></div></div>; }

function Authenticated() { const [user, setUser] = useState(DEMO_USER); const navigate = useNavigate(); useEffect(() => { if (!supabase) return undefined; supabase.auth.getSession().then(({ data }) => { if (data.session) setUser(data.session.user); }); const { data: listener } = supabase.auth.onAuthStateChange((_, session) => setUser(session?.user || DEMO_USER)); return () => listener.subscription.unsubscribe(); }, []); const signOut = async () => { if (supabase) await supabase.auth.signOut(); setUser(DEMO_USER); navigate("/"); }; return <Workspace user={user} onSignOut={signOut} />; }

export default function AppNew() { return <BrowserRouter><Routes><Route path="/" element={<Landing />} /><Route path="/login" element={<Login />} /><Route path="/dashboard/*" element={<Authenticated />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></BrowserRouter>; }
